"""Admission rules for self-improvement data generated by the task agent."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class DataGateDecision:
    accepted: bool
    reasons: tuple[str, ...]


class EpisodeDataGate:
    """Accept only completed, verified, clean episode traces for training data."""

    def evaluate(self, events: Iterable[dict[str, object]]) -> DataGateDecision:
        records = list(events)
        reasons: list[str] = []
        sequences = [record.get("sequence") for record in records]
        if sequences != list(range(len(records))):
            reasons.append("event sequence is not contiguous")
        completed = [record for record in records if record.get("event_type") == "episode_completed"]
        if len(completed) != 1:
            reasons.append("episode must have exactly one completion event")
        elif not bool(_nested(completed[0], "payload", "verification", "success")):
            reasons.append("episode verification did not pass")
        failed_results = [record for record in records if record.get("event_type") == "skill_result" and not bool(_nested(record, "payload", "result", "success"))]
        if failed_results:
            reasons.append("trace includes failed skill attempts; keep for debugging, exclude from training")
        return DataGateDecision(not reasons, tuple(reasons))


def _nested(value: object, *keys: str) -> object | None:
    current: object = value
    for key in keys:
        if not isinstance(current, dict):
            return None
        current = current.get(key)
    return current
